### ISSUE TITLE
Κώδικας C για εξετάστικη

### ISSUE THREAD

**Issue by konstasol** [ikiranis/EAPDocs#10]
https://github.com/konstasol/C_LIBRARY_IN_GREEK_FOR_BEGINNERS-

Αν θέλετε προσθέστε τη βιβλιοθηκη αυτη. Δεν ειναι τιποτα σπουδαιο ειναι η επαναληψη που ειχα κάνει πριν την εξεταστικη όσα πρόλαβα και ανέβασα. 

Επίσης, 

αν θελετε στην ΠΛΗΠΡΟ δεν εχω θέμα να μοιραστω τον κώδικα του Project ( δεν ξερω αν επιτρεπεται βεβαια)
https://github.com/konstasol/GENETIC-ALGORITHM-in-PYTHON-MAXIMIZE-FUNCTION

**Comment by ikiranis** [comment]
Ευχαριστώ. Ενημέρωσα τα docs με τα παραπάνω.
