### ISSUE TITLE
Links προς κεφάλαια βιβλίων Μαθηματικών Σχολικών Βιβλίων

### ISSUE THREAD

**Issue by Chris-Py87** [ikiranis/EAPDocs#2]
Λίστα με links προς συγκεκριμένα κεφάλαια των σχολικών βιβλίων μαθηματικών του Γυμνασίου και του Λυκείου που θεωρούνται προαπαιτούμενα για την επιτυχή ολοκλήρωση της ΘΕ ΠΛΗ12

[Σύνδεσμοι προς βιβλία.docx](https://github.com/ikiranis/EAPDocs/files/5830664/default.docx)

**Comment by ikiranis** [comment]
Ωραίος. Θα το ανεβάσω

**Comment by ikiranis** [comment]
Done. Ανέβηκε. https://github.com/ikiranis/EAPDocs/blob/main/basicMath.md
