### ISSUE TITLE
Proxies του ΕΑΠ για συνεγαζόμενους ιστότοπους

### ISSUE THREAD

**Issue by KostasVam** [ikiranis/EAPDocs#5]
http://proxy.eap.gr/menu

**Comment by ikiranis** [comment]
Τι είναι αυτό?

**Comment by KostasVam** [comment]
Έχει δημιουργήσει διαφορά proxies το ΕΑΠ για να συνδεεσαι σε σάιτ με αρκετό υλικό. Το springer πχ έχει βιβλία τα οποία κατεβάζεις δωρεάν. Τσεκαρε τα και τα υπόλοιπα αν θες.

**Comment by ikiranis** [comment]
Ok. To πρόσθεσα.
