### ISSUE TITLE
Permutation and Combination Calculator

### ISSUE THREAD

**Issue by stamvas** [ikiranis/EAPDocs#7]
https://www.calculator.net/permutation-and-combination-calculator.html?cnv=10&crv=10&x=0&y=0

**Comment by ikiranis** [comment]
Υπάρχει ήδη στα [εργαλεία](https://github.com/ikiranis/EAPDocs/blob/main/general/tools.md) το calculator.net, γενικά σαν site. Δεν έχει νόημα πιστεύω να μπει ξεχωριστά το κάθε calculator, για κάθε περίπτωση υπολογισμού. Έβαλα καλύτερη περιγραφή τώρα, να είναι λίγο πιο ξεκάθαρο τι είναι το συγκεκριμένο site

**Comment by stamvas** [comment]
Ααα οκ. Δεν το ειχα προσεξει
